### ISSUE TITLE
Nightly builds and reproducing builds

### ISSUE THREAD

**Issue by 3ap** [TheElixZammuto/moonlight-xbox#12]
Is it possible to make nightly builds using GitHub CI? I don't have enough experience in the Windows world, so I'm not sure it's as easy as in Linux world.

For example, it would be helpful to check that my changes ([#8](https://github.com/TheElixZammuto/moonlight-xbox/pull/8)) compile successfully at least. Moreover, someone would be able to check my changes and it won't require them to set up a development environment and compile it from scratch (it takes 1 hour+ for me with all VCPKG dependencies).

**Comment by TheElixZammuto** [comment]
The main problem I guess it's to have a GitHub Actions Base optimized for C++ UWP apps, since it's a very niche concept at the moment and I don't know if the vs image covers it, also the build can be very slow for GitHub acrtions too and make the CI iteslf timeout due to the dependencies.

Maybe a first step after than the setup of the base image would be to include the dependencies as library directly as an alternative to vcpkg (something we have done with FFMPEG for Sunshine, see https://github.com/TheElixZammuto/sunshine-prebuilt), in a way that the local environment can be bootstrapped in a friendlier way, what do you think?

**Comment by Nun-z** [comment]
> Is it possible to make nightly builds using GitHub CI? I don't have enough experience in the Windows world, so I'm not sure it's as easy as in Linux world.
> 
> For example, it would be helpful to check that my changes ([#8](https://github.com/TheElixZammuto/moonlight-xbox/pull/8)) compile successfully at least. Moreover, someone would be able to check my changes and it won't require them to set up a development environment and compile it from scratch (it takes 1 hour+ for me with all VCPKG dependencies).

You can reuse the VCPKG folder between builds in order to save time rather than starting from scratch.

**Comment by ReenigneArcher** [comment]
You can change the timeout for steps or an entire job. Although the default is 360 minutes (6 hours). https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

How long does it actually take?

Having pre-built dependencies is a good idea to speed things up.

**Comment by TheElixZammuto** [comment]
So, I managed to make the depencies and start the build (branch github-actions). 
The only missing thing is to pass the certificate correctly using secrets in a way to sign the app, since it's mandatory by the build process

**Comment by ReenigneArcher** [comment]
> So, I managed to make the depencies and start the build (branch github-actions). 
> The only missing thing is to pass the certificate correctly using secrets in a way to sign the app, since it's mandatory by the build process

Is the certificate static or dynamic? Secrets can be added to the repo (or org level) in the settings.

In the workflow you can access the secret like so... `${{ secrets.NAME_OF_YOUR_SECRET }}`

This value won't ever be printed in the logs.
