### ISSUE TITLE
is moonlight using d3d12? if not how is this even possible?

### ISSUE THREAD

**Issue by yamiyugi13** [TheElixZammuto/moonlight-xbox#59]

**Comment by TheElixZammuto** [comment]
The Xbox UWP platform supports both D3D11 and D3D12: https://walbourn.github.io/directx-and-uwp-on-xbox-series-x-s/
This version of Moonlight uses D3D11, since the Video Decoding Library (FFMPEG) uses D3D11 too, also since it's higher level, it is easier to use than D3D12, especially for people without graphics programming experience
