### ISSUE TITLE
Latest Version, input lag only when game is open

### ISSUE THREAD

**Issue by TheRigger** [TheElixZammuto/moonlight-xbox#93]
Hi there,
In the latest retail version, I've encountered the issue of a massive input lag, but only when the game is running and not immediately. The lag increases in the time span of 30 seconds, mainly when playing Baldur's Gate 3.

On the desktop, the lag is fine, but as soon as the game is launched, the lag increases. A strange behavior is that if I change the game resolution, the input lag is back to normal for a bit, and then it starts decreasing again.

Xbox Series S, 60 fps, 1080p.

**Comment by TheElixZammuto** [comment]
Can you please provide the **exact** version that is installed on your console?

**Comment by TheRigger** [comment]
The issue started in 1.14.5 but is present also in 1.14.6.
This issue is appearing only when a second controller is connected.
I don't think it is a matter of stream but rather the input could be an issue

**Comment by j-scrizz** [comment]
Yep, I am getting the same issue also.

**Comment by TheElixZammuto** [comment]
Version 1.14.7 fixes this

**Comment by foreversnoopy** [comment]
I have version 1.15.4.70 on my console.

Same problem : when I connect a second controller, the message "input queue reached maximum size limit" show up repeatedly on the log. Then I get high input latency and can't play properly anymore.

It doesn't matter which order I plug my controllers. I can connect and disconnect any controller, while the app stays open, and everything is fine with one controller but not two at the same time.

Weird thing is, everything was fine over a week ago, then I didn't use the app for almost a week, now the problem is persistent even after reboots of console and computer. I've been trying for a couple of days now.

I have an Xbox One S, with one Xbox One controller, two Xbox Series controllers. I tried all the combinations. I even disabled Geforce Gamestream and switched to Sunshine. Same result.

**Comment by TheElixZammuto** [comment]
> I have version 1.15.4.70 on my console.
> 
> Same problem : when I connect a second controller, the message "input queue reached maximum size limit" show up repeatedly on the log. Then I get high input latency and can't play properly anymore.
> 
> It doesn't matter which order I plug my controllers. I can connect and disconnect any controller, while the app stays open, and everything is fine with one controller but not two at the same time.
> 
> Weird thing is, everything was fine over a week ago, then I didn't use the app for almost a week, now the problem is persistent even after reboots of console and computer. I've been trying for a couple of days now.
> 
> I have an Xbox One S, with one Xbox One controller, two Xbox Series controllers. I tried all the combinations. I even disabled Geforce Gamestream and switched to Sunshine. Same result.

Check #105 instead which is the appropriate issue
